config/routes.rb
Archbiz_app::Application.routes.draw do

root :to => 'home#index'

#pages
get '/about' => 'pages#about'
get '/inspiration' => 'pages#inspiration'
get '/projects' => 'pages#projects'

resources :inquiries, :only => [:new] do
  get 'thank_you', :on => :collection
end

get '/inquiries' => 'inquiries#create'

end

app/models/inquiry.rb
class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper

  attr_accessor :name, :email, :message, :nickname

  validates :name, :presence => true

  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ },
            :presence => true

  validates :message,
            :length => { :maximum => 1000 }

  validates :nickname,
            :format => { :with => /^$/ }

  def initialize(attributes = {})
    attributes = {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default :from => ENV['GMAIL_USERNAME']
  default :to => ENV['GMAIL_USERNAME']

  def new
    @notifier = Notifier.new
  end

  # send inquiry contact email to website owner
  def new_inquiry(name, email, phone, message)
    mail( :to => ENV['GMAIL_USERNAME'],
          :from => ENV['GMAIL_USERNAME'],
          :subject => 'NEW INQUIRY' + ' from ' + name,
          :body => message
        )
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  city            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :city
  has_many :recipes
  has_secure_password

  #    before_save :geocoder
  # private
  # def geocoder
  #   result = Geocoder.search(self.city).first
  #   if result.present?
  #     self.latitude = result.latitude
  #     self.longitude = result.longitude
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
  def ensure_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new
    @message = params[:message]
    @name = params[:name]
    @phone = params[:phone]
    @email = params[:email]
    # Deliver the inquiry_email
    Notifier.new_inquiry(@name, @email, @phone, @message).deliver
    render :new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def inspiration
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_nav
    if @auth.present?
      link_to(@auth.email, login_path, :method => :delete, :class => 'button alert')
    else
      link_to('Login', login_path, :class => 'button success')
    end
  end

    def show_recipe_instructions(instructions, tutorials)
    words = instructions.split.map do |word|
      if word.downcase.in?(tutorials.map(&:name).map(&:downcase))
        link_to(word, Tutorial.where("name ilike ?", word).first)
      else
        word
      end
    end
    words.join(' ')
  end

end

app/views/contact/new.html.haml
#loginform
.row
  .small-2.columns
  .panel.small.small-3.columns
    = form_tag '/contact' do
      = label_tag 'Name'
      = text_field_tag 'name', nil, :autofocus => true
      = label_tag 'Email'
      = text_field_tag 'email'
      = label_tag 'Phone'
      = text_field_tag 'phone'
      = label_tag 'Comments/Questions'
      = text_area_tag 'password'
      = submit_tag 'Submit', :class => 'button radius recipezybtn'
    .cancel_text#cancel_login_form= link_to 'x', root_path
.small-7.columns

app/views/home/_homepage.html.erb
<div id='loginform' class='hide'>
  show form
</div>
<div class="row">
  <div class="6-large columns" id="title-logo">
    <%= link_to (image_tag('seah-hughes-architects-v2.jpg')), root_path %></a>
  </div>
</div>

<div class="6-large-columns intro-text">
  Seah Hughes Architects is a dynamic young architectural practice. We work across a range of project types.
</br>
</br>
  Contact us for a free consultation.
</div>

<!-- Mobile Header -->

<div class="row">
  <div class="twelve columns show-for-small">
  </div>
</div>
<br>

<!-- End Mobile Header -->

<div class="row">
  <div class="small-4.columns">
  </div>
  <div class="row">
    <h6 class="subheader show-for-small">Sort by</h6>
    <div class="small-2.columns">
    </div>
  </div>
</div>

app/views/home/index.html.haml
= render :partial => 'home/homepage'

app/views/inquiries/new.html.haml
#loginform
.row
  .small-2.columns
  .panel.small.small-3.columns
    = form_tag '/inquiries', :method => 'GET' do
      = label_tag 'Name'
      = text_field_tag 'name', nil, :autofocus => true
      .nickname= label_tag 'nickname'
      .nickname= text_field_tag 'nickname'
      = label_tag 'Email'
      = text_field_tag 'email'
      = label_tag 'Phone'
      = text_field_tag 'phone'
      = label_tag 'Message'
      = text_area_tag 'message'
      = submit_tag 'Submit', :class => 'button radius recipezybtn'
    .cancel_text#cancel_login_form= link_to 'x', root_path
.small-7.columns

#thankyou

app/views/inquiries/thank_you.html.haml
Thank you!

app/views/inquiries/thank_you.js.erb
$('#thankyou').append('<%=j render(:partial => 'thank_you') %>');

app/views/layouts/_footer.html.erb
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Nicky Hughes Rails App 2013.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="http://nickyonrails.tumblr.com/" target='_blank'>Blog</a></li>
            <li><a href="http://nickyh.github.com/" target='_blank'>Portfolio</a></li>
            <li><a href="https://twitter.com/nichug00" target='_blank'>Twitter</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_login.html.haml
.row
  .small-2.columns
  .panel.small-3.columns
    = form_tag '/login' do
      = label_tag 'email'
      = text_field_tag 'email', nil, :autofocus => true
      = label_tag 'password'
      = password_field_tag 'password'
      = submit_tag 'Sign in', :class => 'button radius'
    .cancel_text.has-tip= link_to 'x', recipes_path, :id => 'cancel_login_form', :title => 'cancel login'
.small-7.columns

app/views/layouts/_nav.html.erb
  <nav class="top-bar">
    <ul class="title-area">

    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-dropdown">
          <li id='contactlink'><%= link_to('Contact', new_inquiry_path, :id => 'navtablog') %></li>
          <li id='contactlink'><%= link_to('Projects', projects_path, :id => 'navtablog') %></li>
          <li class="divider"></li>
      </ul>
<div id='loginform' class='hide'>

</div>
    </section>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Seah Hughes Architects</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="background-image">

      <%= yield %>

      <%= render :partial => 'layouts/nav' %>

    </div>
    <script>
    $(document).foundation();
    </script>
  </body>
</html>

app/views/pages/inspiration.html.haml
Some of our favourite buldings

app/views/pages/projects.html.haml
Projects!

app/views/users/_form.html.haml
.row
  .panel
    .small-3.small-centered.columns
    %h5= 'Sign up!'
    = form_for @user, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.label :city
      = f.text_field :city
      = f.submit nil, :class => 'button radius', :remote => true

app/views/users/_users.html.haml
- @users.each do |user|
  %li= user.email

app/views/users/create.js.erb
$('#new_user').empty();
$('#users').empty();
$('#users').append('<%=j render(:partial => 'users') %>');

app/views/users/index.html.haml
%h1= 'find foodies in your area!'

/ = button_tag 'Map', :class => 'button radius tiny', :id => 'show_map'

/ .large-6.columns
/   #map_canvas
/   %script
/     = "display_map(#{@auth.lat}, #{@auth.long}, 2);"

app/views/users/new.html.haml
.row
  .panel
    .small-7.small-centered.columns
      %h1= 'New User'
.row
  = render(:partial => 'form')

app/views/users/new.js.erb
$('#new_user').append('<%=j render(:partial => 'form') %>');

app/views/users/show.html.haml
%h1= 'find foodies in your area!'

.row
  #map_canvas
    / %script
    /   = "display_map(#{@auth.latitude}, #{@auth.longitude}, 2);"



/ - Users.each do |user|
/   - @cities = user.map(&:city)

/ = select_tag 'Location', options_for_select(@cities.map{ |a| [a, a] })

/ = button_tag 'Find', :class => 'button radius tiny', :id => 'show_map'